import CryptoKit
import Foundation

/// Entitlement level. `commercial` use is governed by the EULA (a legal term, not
/// a code gate) — there is deliberately no `commercial` case here. Only `free`
/// (the default; no key) and `pro` (a signed license unlocks the paid features)
/// are technically enforced.
enum LicenseTier: String {
    case free
    case pro
}

/// What a verified license carries.
struct LicensePayload {
    let name: String      // who it was issued to (shown in Settings)
    let tier: LicenseTier
}

/// Offline license verification. A license key is `base64url(payload).base64url(sig)`
/// where `payload` is a tiny JSON object (`{name, tier, iat}`) and `sig` is an
/// Ed25519 signature over those exact payload bytes. We verify against the public
/// key baked in below; the matching private key (which mints keys) never ships.
///
/// No network, no account — verification is a single signature check, so a license
/// keeps working forever, offline, exactly per the product's "no login for core
/// function" principle. The trade-off (a determined user could patch the binary to
/// skip the check) is accepted: the EULA covers commercial use, and the honest
/// $24 buyer was never the threat.
enum License {
    /// Ed25519 public key (base64, raw 32 bytes) that validates license keys.
    ///
    /// DEV KEY — generated by scripts/gen-keypair.swift for development/testing.
    /// Before any public release, regenerate the pair and replace this, keeping the
    /// private half OFFLINE. Rotating it invalidates every license already issued.
    private static let publicKeyB64 = "fU82foP+k9x5MzK4CJ104ImU1WhNZ7oxrOAdrXZIgm8="

    /// Returns the payload iff the key's signature is valid for our public key.
    /// `nil` for an empty, malformed, or forged key (caller treats nil as `free`).
    static func verify(_ licenseKey: String) -> LicensePayload? {
        let parts = licenseKey.split(separator: ".", maxSplits: 1)
        guard parts.count == 2,
              let payload = b64urlDecode(String(parts[0])),
              let sig = b64urlDecode(String(parts[1])),
              let pubData = Data(base64Encoded: publicKeyB64),
              let pub = try? Curve25519.Signing.PublicKey(rawRepresentation: pubData),
              pub.isValidSignature(sig, for: payload),
              let obj = (try? JSONSerialization.jsonObject(with: payload)) as? [String: Any],
              let tierStr = obj["tier"] as? String,
              let tier = LicenseTier(rawValue: tierStr)
        else { return nil }
        return LicensePayload(name: (obj["name"] as? String) ?? "", tier: tier)
    }

    /// Base64url (RFC 4648 §5, no padding) → Data, tolerating the standard alphabet
    /// too. Re-pads to a multiple of 4 before decoding.
    private static func b64urlDecode(_ s: String) -> Data? {
        var t = s.replacingOccurrences(of: "-", with: "+")
                 .replacingOccurrences(of: "_", with: "/")
        while t.count % 4 != 0 { t += "=" }
        return Data(base64Encoded: t)
    }
}
